---
- name: print env var
  become: yes
  shell: echo $TYPEORM_CONNECTION
  register: dir_structure
  tags: t1

- debug:
    var: dir_structure.stdout
  tags: always
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  community.general.npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: print env var
  become: yes
  shell: echo $TYPEORM_CONNECTION
  register: dir_structure1
  tags: t1

- debug:
    var: dir_structure1.stdout
  tags: always
