---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  community.general.npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Basic usage 1
  ansible.builtin.debug:
    msg: "'{{ lookup('ansible.builtin.env', 'HOME') }}' is the HOME environment variable."

- name: Basic usage 2
  ansible.builtin.debug:
    msg: "'{{ lookup('ansible.builtin.env', 'TYPEORM_ENTITIES') }}' is the TYPEORM_ENTITIES environment variable."

- name: Basic usage 3
  ansible.builtin.debug:
    msg: "'{{ lookup('env', 'TYPEORM_ENTITIES') }}' is the TYPEORM_ENTITIES environment variable."
