version: 2.1

orbs: 
  slack: circleci/slack@4.10.1

jobs:
  build-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: cd frontend && npm install
      - run: cd frontend && npm run build

  build-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm run build

  test-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: cd frontend && npm install
      - run: cd frontend && npm run test

  test-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm run test

  scan-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: cd frontend && npm install
      - run: cd frontend && npm audit fix --audit-level=critical --force
      - run: cd frontend && npm audit --audit-level=critical
      - slack/notify:
          event: pass
          template: basic_success_1
          channel: C03DAJYL3SM
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: C03DAJYL3SM

  scan-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: cd backend && npm install
      - run: cd backend && npm audit fix --audit-level=critical --force
      # - run: cd backend && npm audit --audit-level=critical
      - slack/notify:
          event: pass
          template: basic_success_1
          channel: C03DAJYL3SM
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: C03DAJYL3SM

workflows:
  build_and_test:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - scan-backend:
          requires: [build-backend]
          context: slack
      - scan-frontend:
          context: slack
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
