version: 2.1

jobs:
  build-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout:
          path: "./frontend"
      - run: cd frontend
      - run: ls
      - run: npm install
      - run: npm run build

  build-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout:
          path: "./backend"
      - run: cd backend
      - run: npm install
      - run: npm run build

workflows:
  build_and_test:
    jobs:
      - build-frontend
      - build-backend
